### PR TITLE
Final sprint

### PR DESCRIPTION
**Pull request by jorgegil**

### CODE REVIEW

**Comment by laurensversluis** [comment]
Hi Jorge,

I was trying to load the plugin but asked me for a missing layers. Will VDM have this database already elsewhere stored?

Laurens

On 13 Mar 2017, at 22:28, Jorge Gil <notifications@github.com<mailto:notifications@github.com>> wrote:


Merged #1<https://github.com/jorgegil/kpo-pilot/pull/1>.

**Comment by jorgegil** [comment]
Hi Laurens,
If you download the zip file from the beta release you can test it, it includes the data in the data folder.

I had meetings on Monday at the VDM and yesterday at the ministry, and have a long list of to-do items... But overall people are very pleased with the outcome.
The final release will be made on Sunday, the workshop is on Monday afternoon.

(I took out the translation feature that you created, but will put it back in for the final or posterior release.)

**Comment by laurensversluis** [comment]
Hi Jorge,

The tool works really well and looks amazing! You have been a busy man indeed! Well done!

Laurens

On 15 Mar 2017, at 19:07, Jorge Gil <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Laurens,
If you download the zip file from the beta release you can test it, it includes the data in the data folder.

I had meetings on Monday at the VDM and yesterday at the ministry, and have a long list of to-do items... But overall people are very pleased with the outcome.
The final release will be made on Sunday, the workshop is on Monday afternoon.

(I took out the translation feature that you created, but will put it back in for the final or posterior release.)

**Comment by jorgegil** [comment]
Hi Laurens,

Thanks for the feedback!

And you should check out the final release, following the experience from the workshop. The usability is much improved.

Cheers,
Jorge

**Pull request merged**
